# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST  http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/bc82218b-e8bc-46bf-838d-91d26eab8681/transcription
Content-Type: application/json

{
    "prompt": "erlang,elixir"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/generate
Content-Type: application/json

{
    "videoId": "eb989a3f-ce9f-4124-8807-71d8e783aeb0",
    "temperature": 0.5,
    "template": "Summarize the following video's transcription: '''{transcription}''' "
}